language: node_js
node_js: v10.8.0
services:
- postgresql
before_script:
- psql -c "CREATE DATABASE test_sms_manager_db;"
install:
- yarn install
script:
- yarn test:coverage
- yarn coveralls
deploy:
  provider: heroku
  api_key:
    secure: JJoAPU6ZfRLijCDoHjjEAFwP/Jxsv829+UNzJR7VGZOZofa8eUi+SgWzL4fe7ekOfAEAEc/aNXM+4bmYbQbwcDfoVLPnK8+arQ7gK0SmmGVXSGqzLImZpZN+K4Q6KJ9kFoyKSRvj5E6KU9XtwfkRTtSZFMoUcQEq/xCD+Yr+MCkLoxvn7ck88rHEFzHSDqt1zm1p13v6SCwsjynmOIAvtxtmydgPqYGxVfWYKAeBFLEc8KVxqW0Rvx6D47l0pq3CwnAE2zCmC9xG/2u91I30uPp54/3D58xqm9mZ0Hr18Ckw8O3UxnUTrJWeQFoafb+O9btiMxluWFHLZZmUcZCZNcCuC+DrKaD/9bASCdXetoYZkoup9gIznShwEKVuE6Kbe1fmv4tRtHEBbONb4taxYsKSlF4gLYgjW1og3NFFPxHGnXBTvMFSokBXU5rrlJAyOEBEMs8FcRkxhXQ1OymgO8caxi0uk1r8mXQm+pIp6ExE4+aIeKtupElHcUIDlMLfElwGAAyRRgAMHlz424HWDw2z7E94dSsCCUs1BA+79ob9yLmsaS539l7TyQ+uVxF4IhyJbKdLw34njXyPK5BcMaqVmdJVoScCqonhvOC51QJAN65wN3Rczyv9DcHjUw/NakW59+uA9ZzduifAXdgNAQwF/2nJOwRC/cs1bShbFLs=
  app: sms-manager-api-cj
  on:
    branch: master
